Doc: update readme
betagouv/transition-ecologique-entreprises-widget pull request #176
Opened 2023-10-23 10:30 UTC by yvalentin

### FYI 
This branch come from `feature/update-node` [branch](https://github.com/betagouv/transition-ecologique-entreprises-widget/tree/feature/update-node)  
So feature/update-node` need to be merge before ;-)

### What's done
- A menu has been add at the beginning of the readme
- The main screenshot has been updated to correspond to the main page of the current version
- A `quick start` part has been added to give command to just start the project quickly on local machine
- Some commands has been corrected
- A new part `Development mode` has been added to give command to run the project has a developer and work on the project
- Credits part has been updated

2023-10-25 12:41 UTC, JulienParis requested changes

2023-10-25 12:41 UTC, JulienParis commented on packages/web/package.json
Isn't it redondant with #167 ?

2023-10-25 12:41 UTC, JulienParis commented on packages/web/.env.example
> +VITE_BREVO_SENDER_EMAIL=france-transition@beta.gouv.fr
There is no need for this line anymore

2023-10-25 12:41 UTC, JulienParis commented on packages/backend/package.json
Isn't it redundant with #167 ?

2023-10-25 12:41 UTC, JulienParis commented on package.json
> +    "node": "~18.18",
Isn't it redundant with #167 ?

2023-10-25 12:41 UTC, JulienParis commented on README.md
> +- Front: [VueJS](https://vuejs.org/) (v3)
Perhaps we could mention the DSFR package here, just make it more visible from the start ? 

```md
- Design system: [DSFR](https://www.systeme-de-design.gouv.fr/)
```

2023-10-25 12:41 UTC, JulienParis commented on .nvmrc
Isn't it redundant with #167 ?

2023-10-25 12:41 UTC, JulienParis commented on .github/workflows/tests.yml
Isn't it redundant with #167 ?

2023-10-25 12:47 UTC, JulienParis commented
praise: nice PR ! the `start-*` scripts are quite a bonus for people just wanting to test without having to play w/ `.env` files. I noted the branch `feature/update-node` should be merged first, I just noted all the comments about #167 as questions (just beginning to adopt [conventional comments](https://conventionalcomments.org/) )

2023-10-26 07:43 UTC, JulienParis requested changes

2023-10-26 07:43 UTC, JulienParis commented on README.md
>  - the ["backend" workspace](./packages/backend/README.md) contains the back-end implementations.
todo: I just saw this this morning, the `data` workspace information is missing =>

```md
- the ["data" workspace](./packages/data/README.md) contains the datasets and common files for datasets builds.
```

2023-11-02 14:14 UTC, yvalentin commented on packages/web/vite.config.ts
I have done a rollback on this

2023-11-02 16:35 UTC, merged