Refactor/eslint
betagouv/transition-ecologique-entreprises-widget pull request #373
Opened 2023-11-30 16:12 UTC by yvalentin

// Pas encore eu le temps de décrire cette PR

2023-12-01 10:25 UTC, pierrecamilleri requested changes
Super, merci ! 
Personnellement je trouve ces configurations toujours très très fastidieuses, je suis curieux si tu partages cette expérience ou si tu as un moyen de simplifier la procédure ?

2023-12-01 10:25 UTC, pierrecamilleri commented on packages/data/src/dataPipeline.ts
>  import type { Dispositif as ProgramWithoutId } from './generated/program'
Même remarque que précédemement, cette ligne ne devient valide qu'après avoir build le projet (plus précisément `npm run build-json-output -w packages/data`)
D'ailleurs, ça casse la CI, qui ne build pas avant les tests unitaires.

2023-12-01 10:25 UTC, pierrecamilleri commented on packages/web/package.json
>      "type-check": "vue-tsc --noEmit -p tsconfig.vitest.json --composite false",
```suggestion
    "type-check": "vue-tsc --noEmit -p tsconfig.json --composite false",
```

2023-12-01 10:57 UTC, JulienParis commented
#asymétriedinfos : @pierrecamilleri on a un peu discuté hier avec Yohann de ses travaux sur le linting, et je lui ai demandé de créer cette PR draft juste pour commencer à étudier et relire les changements grâce au diff. 

Par contre (et là c'est encore uniquement ma propre pratique) je ne commence pas de review ou n'apporte pas de commentaires tant que la PR est en draft et non en "ready for review" afin de laisser la personne qui bosse sur la branche le temps nécessaire à faire ce qu'elle a à faire.

2023-12-04 11:40 UTC, JulienParis reviewed
note: quelques questions sur la commodité d'une règle _eslint_, mais sinon ok du pur point de vue de la logique et de l'implémentation.

issue: Pour la partie pratique par contre j'ai testé localement après avoir fait un simple `npm update` + `npm run lint` +  `npm run build-front`, et j'ai ~6 erreurs. J'imagine que ce souci sera réglé après _merge_ de la partie concernant le _front_ uniquement, mais c'était essentiellement pour le signaler et éviter qu'on _merge_ cette branche avant que l'ensemble ne puisse être bien buildé en environnement de `preprod`.

praise : Sacré taf en tout cas, bravo pour cette première partie du taf sur le linting

2023-12-04 11:40 UTC, JulienParis commented on packages/backend/src/helpers/objects.ts
> +export function filterObject<T extends object>(obj: T, fn: (entry: Entry<T>, i: number, arr: Entry<T>[]) => boolean): Partial<T> {
question: ce formatage automatique `one-liner` est-il considéré comme obligatoire / bonne pratique et pourquoi ? Personnellement j'aime bien avoir une ligne par paramètre à partir du moment où il y en plusieurs car je trouve cela plus lisible sur un éditeur.

2023-12-04 11:40 UTC, JulienParis commented on tsconfig.json
> +    "baseUrl": ".",
question: pour ma culture générale, qu'est-ce que cette précision permet d'éviter comme erreurs ?

2023-12-04 12:00 UTC, pierrecamilleri commented on packages/backend/src/controller/app.ts
> -// @ts-ignore // routes generated at build time by tsoa
ok pour moi

2023-12-06 14:22 UTC, yvalentin commented on packages/backend/src/helpers/objects.ts
> +export function filterObject<T extends object>(obj: T, fn: (entry: Entry<T>, i: number, arr: Entry<T>[]) => boolean): Partial<T> {
Tu penses à se genre de règle ?
https://eslint.style/rules/js/function-paren-newline

avec `multiline-arguments`

2023-12-06 14:24 UTC, yvalentin commented on packages/backend/src/helpers/objects.ts
> +export function filterObject<T extends object>(obj: T, fn: (entry: Entry<T>, i: number, arr: Entry<T>[]) => boolean): Partial<T> {
Pour répondre a ta premier question.  
Ici, c'est une configuration par défaut, avec très peu de configuration de règles.

Comme préciser dans la PR:
> Toutes ces configurations peut bien sûr évoluer dans le temps par échange des besoin avec équipe tech.

Donc, tout à fait d'accord pour faire évoluer les règles en fonction de chacun ;-)

2023-12-06 14:33 UTC, JulienParis commented on packages/backend/src/helpers/objects.ts
> +export function filterObject<T extends object>(obj: T, fn: (entry: Entry<T>, i: number, arr: Entry<T>[]) => boolean): Partial<T> {
Oui c'est bien à cette règle à laquelle je pensais ! ... mais avant de pousser pour qu'on l'implémente / intègre je me pose la question de vos pratiques et habitudes respectives @yvalentin @pierrecamilleri. Perso j'aime bien cette règle

2023-12-06 14:36 UTC, pierrecamilleri commented on packages/backend/src/helpers/objects.ts
> +export function filterObject<T extends object>(obj: T, fn: (entry: Entry<T>, i: number, arr: Entry<T>[]) => boolean): Partial<T> {
Je vote pour :raised_hand:

2023-12-06 16:01 UTC, yvalentin commented on tsconfig.json
> +    "baseUrl": ".",
C'est pour définir le rootDir lors de la résolution des path pour les chemin relatif

2023-12-08 13:46 UTC, JulienParis commented on packages/backend/src/helpers/objects.ts
> +export function filterObject<T extends object>(obj: T, fn: (entry: Entry<T>, i: number, arr: Entry<T>[]) => boolean): Partial<T> {
j'y pense juste, mais si on intègre cette règle je me dis qu'il faudrait pe la reporter également dans la PR #392, où un certain nombre de modifs sont aussi dues au linting des fonctions selon une autre règle.

2023-12-08 14:22 UTC, pierrecamilleri approved these changes

2023-12-11 13:24 UTC, JulienParis commented
Note pour plus tard : attention, résoudre les conflits avec `preprod` > à faire après merge de #392 ([refactor/eslint](https://github.com/betagouv/transition-ecologique-entreprises-widget/tree/refactor/eslint) from [refactor/eslint-web](https://github.com/betagouv/transition-ecologique-entreprises-widget/tree/refactor/eslint-web)) et avant merge vers `preprod`

2023-12-13 09:45 UTC, JulienParis commented
@yvalentin Si ça t'embête pas je voudrais juste pusher un commit qui enlève les warnings sur les `must be hyphenated  vue/v-on-event-hyphenation` (ou faire une mini-PR si tu préfères)

2023-12-13 11:26 UTC, JulienParis approved these changes

2023-12-13 11:32 UTC, merged