Refactor/lint attributes per line 406
betagouv/transition-ecologique-entreprises-widget pull request #422
Opened 2023-12-13 14:03 UTC by JulienParis

solves #406

2023-12-13 16:30 UTC, yvalentin requested changes
- [x] revoir la config avec prettier
- Perso, je suis ok pour le "singleAttributePerLine" mais pas vraiment pour "bracketSameLine"

Voir aussi: https://eslint.vuejs.org/rules/max-attributes-per-line

2023-12-15 09:47 UTC, JulienParis commented on .prettierrc.json
> +  "bracketSameLine": true
Personnellement il y a là une question d'habitudes davantage que de process car intégrer cette règle dans cette PR ne me semble pas mériter une PR à part. 

Je pense qu'ici peut trancher directement sur cette PR : personnellement je trouve que la règle du `bracketSameLine` rend le html plus agréable à la lecture, mais ça reste assez personnel. Si de ton côté tu y es opposé je veux bien comprendre pourquoi, et je ne suis a priori pas contre le fait de ne pas mettre cette règle du tout si elle te semble qu'elle nous dessert davantage qu'elle nous sert.

2023-12-15 09:52 UTC, JulienParis commented
> * [ ]  revoir la config avec prettier
> 
>     * Perso, je suis ok pour le "singleAttributePerLine" mais pas vraiment pour "bracketSameLine"
> 
> 
> Voir aussi: https://eslint.vuejs.org/rules/max-attributes-per-line

J'avais commencé en implémentant la règle ESLint `max-attributes-per-line` mais d'après ce que j'ai compris les règles Prettier écrasent les règles ESLint ([ref](https://blog.logrocket.com/using-prettier-eslint-automate-formatting-fixing-javascript/) mais il y a bon nombre de sujets du genre sur StackOverflow)

2023-12-18 09:35 UTC, yvalentin commented
> > * [x]   revoir la config avec prettier
> >   
> >   * Perso, je suis ok pour le "singleAttributePerLine" mais pas vraiment pour "bracketSameLine"
> > 
> > Voir aussi: https://eslint.vuejs.org/rules/max-attributes-per-line
> 
> J'avais commencé en implémentant la règle ESLint `max-attributes-per-line` mais d'après ce que j'ai compris les règles Prettier écrasent les règles ESLint ([ref](https://blog.logrocket.com/using-prettier-eslint-automate-formatting-fixing-javascript/) mais il y a bon nombre de sujets du genre sur StackOverflow)

Il y a déjà `eslint-config-prettier`' dans la partie web avec `@vue/eslint-config-prettier`...  
On peux voir pour l'ajouter dans le package global pour l'ajouter sur la partie `backend` et `data`

2023-12-18 09:41 UTC, yvalentin commented on package.json
> +    "eslint-plugin-prettier": "^5.0.1",
suggestion: Ajouter une version plus récent car c'est celle que l'on a déjà pour @vue/eslint-config-prettier

```json
"eslint-config-prettier": "^8.8.0",
```

2023-12-18 09:55 UTC, yvalentin commented on .prettierrc.json
> +  "bracketSameLine": true
L'idée de la Pr unique par règle et justement de pouvoir discuter indépendament de chaque regles et d'accepter ou pas les règles une par une...  

Pour le `bracketSameLine` et en ce basant sur un exemple concret (après bien sur c'est sujbectif), je trouve plus lisible **sans** le `bracketSameLine` que avec :

Sans :
![image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/1521862/ef09d1e9-c161-4db3-a838-8319f3912029)

Avec:
![image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/1521862/0d69516f-12eb-49e7-87af-a4ac4e2a3072)


Après comme on est trois ;-) on peux aussi demander à @pierrecamilleri de trancher !?

2023-12-18 12:51 UTC, pierrecamilleri commented on .prettierrc.json
> +  "bracketSameLine": true
Merci pour le ping. 

J'ai personnellement une préférence pour un retour à la ligne pour les fermetures de symboles "d'encadrement" (`()`, `{}`, `<>`...). Ca crée des sauts d'indentation réguliers qui aident à se repérer. 

L'exemple de Yohann est parlant je trouve, la première version permet d'identifier à première vue le début du contenu encadré par les balises `<router-link>`, alors que dans le second, ça se mélange visuellement avec les attributs de la balise ouvrante.

2023-12-19 11:53 UTC, JulienParis commented on .prettierrc.json
> +  "bracketSameLine": true
Ok, le scrutin a parlé. Let's go alors. Je laisse le `bracketSameLine` de côté

2023-12-19 13:15 UTC, yvalentin commented on package.json
> +    "eslint-plugin-prettier": "^5.0.1",
Ah oups !! My bas !

2023-12-19 13:19 UTC, yvalentin commented on package.json
> +    "eslint-plugin-prettier": "^5.0.1",
Dans `vue/eslint-config-prettier`, il y a les deux ;-)  
##### package-lock.json de web :

```json
"node_modules/@vue/eslint-config-prettier": {
      "version": "8.0.0",
      "resolved": "https://registry.npmjs.org/@vue/eslint-config-prettier/-/eslint-config-prettier-8.0.0.tgz",
      "integrity": "sha512-55dPqtC4PM/yBjhAr+yEw6+7KzzdkBuLmnhBrDfp4I48+wy+Giqqj9yUr5T2uD/BkBROjjmqnLZmXRdOx/VtQg==",
      "dev": true,
      "dependencies": {
        "eslint-config-prettier": "^8.8.0",
        "eslint-plugin-prettier": "^5.0.0"
      },
      "peerDependencies": {
        "eslint": ">= 8.0.0",
        "prettier": ">= 3.0.0"
      }
    },
```

2023-12-19 13:21 UTC, yvalentin approved these changes

2024-01-18 20:38 UTC, merged