feat[brevo]: envoi d'opportunités dans Brevo
betagouv/transition-ecologique-entreprises-widget pull request #502
Opened 2024-01-18 08:58 UTC by pierrecamilleri

2024-01-22 16:11 UTC, yvalentin requested changes

2024-01-22 16:11 UTC, yvalentin commented on packages/backend/src/opportunity/infrastructure/api/brevo/brevoContact.ts
> +function convertDomainToBrevoContact(contact: ContactDetails, optIn: true): ContactAttributes {
nitpick: ajouter un saut de ligne entre la const et la function

2024-01-22 16:11 UTC, yvalentin commented on packages/backend/tests/opportunity/createOpportunity.test.ts
> +import { Maybe, Result } from 'true-myth'
Praise: Trop cool pour les tests !

2024-01-24 10:02 UTC, pierrecamilleri reviewed
Merci pour la review ! 
J'ai pris en compe les petits points, il y a deux remarques sur lesquelles j'aimerais bien avoir ton retour avant de modifier. 

Par ailleurs, j'ai constaté qu'une adresse email invalide conduit toujours à une erreur 500 (erreur 400 de l'API Brevo non spécifiquement traitée). Je pense qu'il faudra faire de la validation côté serveur (côté client, il y a déjà ce ticket : #262), mais que ça peut attendre à ce stade. Je crée un ticket ?

2024-01-24 11:16 UTC, yvalentin commented on packages/backend/src/opportunity/domain/opportunityFeatures.ts
> +          const opportunityUpdateErr = await this._updateOpportunitySentToBpifrance(opportunityId, operatorResult.isOk)
Est-ce qu'il serai possible d'avoir le champs opérateur  dans les opportunités de Brevo. Et d'avoir ensuite uniquement `Envoyé: Oui/Non` ?

2024-01-24 11:21 UTC, yvalentin commented on packages/backend/src/opportunity/infrastructure/api/brevo/types.ts
> +export enum HttpMethod {
La method de axios prend aussi les `string`
```
method?: Method | string;
```
Alors moi, ça me dérange pas d'avoir `HttpMethodType[HttpMethod.POST]`

Après pas de souci non plus pour avoir dans les interfaces:
```
method: HttpMethod.POST
```

Alors, je dirais comme tu veux ;-)

2024-01-24 11:24 UTC, yvalentin commented
> Par ailleurs, j'ai constaté qu'une adresse email invalide conduit toujours à une erreur 500 (erreur 400 de l'API Brevo non spécifiquement traitée). Je pense qu'il faudra faire de la validation côté serveur (côté client, il y a déjà ce ticket : #262), mais que ça peut attendre à ce stade. Je crée un ticket ?

Oui, c'est sur que d'avoir un/des validateurs pour le back serai fort utile !
A mon avis, le mieux c'est de traiter les deux en même temps.
Alors créer une nouveau ticket : Ok mais est-ce que tu peux le lier au ticket #262 ?

2024-01-24 14:31 UTC, yvalentin commented
> > Par ailleurs, j'ai constaté qu'une adresse email invalide conduit toujours à une erreur 500 (erreur 400 de l'API Brevo non spécifiquement traitée). Je pense qu'il faudra faire de la validation côté serveur (côté client, il y a déjà ce ticket : #262), mais que ça peut attendre à ce stade. Je crée un ticket ?
> 
> Oui, c'est sur que d'avoir un/des validateurs pour le back serai fort utile ! A mon avis, le mieux c'est de traiter les deux en même temps. Alors créer une nouveau ticket : Ok mais est-ce que tu peux le lier au ticket #262 ?

d'ailleurs: #470

2024-01-24 16:04 UTC, yvalentin commented on packages/backend/src/opportunity/infrastructure/api/brevo/types.ts
> +// Payloads
suggestion: J'avais apprécié la déclaration de ce type:
```
export type BrevoRequestData = BrevoPostContactData | BrevoGetContactData | BrevoPostDeal | BrevoLinkDealData | BrevoPatchDealData
```

Qui peut être utilisé sur la classe BrevoAPI
```
private async _request(data: BrevoRequestData): Promise<Result<AxiosResponse, Error>> {
```

De plus, la method a disparu dans les interfaces de `BrevoRequestData`  
Je pense que le minimum c'est quand même:
```
method: 'post'
```

2024-01-25 08:59 UTC, pierrecamilleri commented on packages/backend/src/opportunity/infrastructure/api/brevo/types.ts
> +// Payloads
Ah, après relecture je trouvais que ces types étaient un peu maladroits, car en partie redondant avec l'implémentation (sur la partie `method` et `url`). Du coup, en rendant `_request` privée, et en créant des méthodes publiques spécialisées `PostContact` etc. dans la classe `BrevoAPI` j'enlevais cette redondance, et ne conservait que les types relatifs aux payloads. 

Eventuellement, on peut imposer que `method` et `url`  soient requis dans `_request` : 

```
interface BrevoRequestData extends AxiosRequestConfig {  
  method: Axios.method
  url: string
}
```

Ca te conviendrait comme ça ?

2024-01-25 09:36 UTC, pierrecamilleri commented on .github/workflows/tests.yml
> +      - run: npm run spec-and-routes -w packages/backend
Car besoin du type généré  dans "build-json-output" `Operators` pour exécuter sans erreur `spec-and-routes`

2024-01-26 14:32 UTC, pierrecamilleri commented
Discuté aujourd'hui avec @yvalentin : 
- Possibilité de factoriser les deux appels de `_getProgramById`
- Typer un peu plus précisément `BrevoRequestData` en ajoutant `data?: xxxPayload | yyyPayload | etc`
- Les payloads n'`extend` plus `AxiosRequestConfig` > à retirer

2024-01-31 09:00 UTC, yvalentin approved these changes

2024-01-31 09:20 UTC, pierrecamilleri commented on packages/backend/src/opportunity/infrastructure/api/brevo/types.ts
> +  LESS_THAN_20 = 1,
Oui, c'est ça !

2024-01-31 09:21 UTC, merged