fix(dependabot): update package security
betagouv/transition-ecologique-entreprises-widget pull request #517
Opened 2024-01-24 10:04 UTC by yvalentin

#### Fixed dependence securities issues

- https://github.com/betagouv/transition-ecologique-entreprises-widget/security/dependabot 
  - https://github.com/betagouv/transition-ecologique-entreprises-widget/security/dependabot/21
  - https://github.com/betagouv/transition-ecologique-entreprises-widget/security/dependabot/20
    - [(vite): update vite dependency and update breaking change](https://github.com/betagouv/transition-ecologique-entreprises-widget/pull/517/commits/afe47dc7ff7ea98e302293ad9a216cc78f877654)
    - [fix: vitest package updated](https://github.com/betagouv/transition-ecologique-entreprises-widget/pull/517/commits/73b85126bf3d0d689f025782e7e003db92b25910)
  - https://github.com/betagouv/transition-ecologique-entreprises-widget/security/dependabot/20
    - [fix: Follow Redirects package security](https://github.com/betagouv/transition-ecologique-entreprises-widget/pull/517/commits/07b7d53821fc81052fc95920be8297d1044cdbdc)
  - https://github.com/betagouv/transition-ecologique-entreprises-widget/security/dependabot/9
    - [fix: Cypress package security](https://github.com/betagouv/transition-ecologique-entreprises-widget/pull/517/commits/780f5780119a205ba3b97ec7e1f5c47b474f5302)

2024-01-24 15:12 UTC, pierrecamilleri approved these changes
:pray:

2024-01-24 15:12 UTC, pierrecamilleri commented on packages/web/package.json
> -    "cypress": "^12.7.0",
On a des tests cypress fonctionnels ? Si ce n'est pas le cas, je serais autant pour supprimer la dépendance et les tests (à moins que quelqu'un ait l'intention de les retravailler un jour ?)

2024-01-24 15:12 UTC, pierrecamilleri commented on packages/web/tsconfig.json
> +    "experimentalDecorators": true,
J'ai peut-être loupé mais je n'en ai pas vu l'usage dans le package "web".

2024-01-29 04:20 UTC, JulienParis requested changes
Pas testé localement, je me demandais juste si les montées de versions de `vite` et `vitest` pouvaient avoir un quelque impact alors que la version de `vue` reste la même.

2024-01-29 04:20 UTC, JulienParis commented on packages/web/tsconfig.json
> +    "experimentalDecorators": true,
Même remarque que Pierre, d'autant que tant que les `experimentalDecorators` n'ont pas l'air de faire tout à fait "officiellement" de JS ([source](https://www.typescriptlang.org/tsconfig#experimentalDecorators))

2024-01-29 16:04 UTC, merged