feat : add clearable btn for search input (feat not existing in dsfr)
betagouv/transition-ecologique-entreprises-widget pull request #593
Opened 2024-02-21 16:42 UTC by JulienParis

solves #280

2024-02-22 09:05 UTC, yvalentin commented on packages/web/src/components/tracks/TeeTrackInput.vue
> +  <TeeTrackInputWrapper
suggestion: Il me semble plus simple de mettre en place le dsfrSearchBar qui contient le button "clearable"

https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/barre-de-recherche
https://vue-dsfr.netlify.app/?path=/docs/composants-dsfrsearchbar--docs 
https://docs.vue-ds.fr/types#dsfrsearchbar

2024-02-22 15:30 UTC, JulienParis commented on packages/web/src/components/tracks/TeeTrackInput.vue
> +  <TeeTrackInputWrapper
Comme je disais il y a quelques temps déjà je suis pas fan de la lib vue-dsfr, et je ne vois pas où se trouve le bouton "clear" en plus du bouton d'action principal (bouton bleu avec la loupe). A priori on n'a qu'un seul bouton dispo dans les 2 libs.

Notre composant reprend effectivement déjà les principales specs de la barre de recherche DSFR, le bouton de la barre de recherche étant auparavant uniquement celui de la petite loupe pour lancer la recheche, mais comme on a besoin d'un bouton en plus et qu'on a eu besoin de modifier différentes petites choses (largeur, hauteur, comportement responsive, styles...) j'ai préféré rester sur le DSFR et non me baser sur la lib vue-dsfr

2024-02-22 16:08 UTC, yvalentin commented on packages/web/src/components/tracks/TeeTrackInput.vue
> +  <TeeTrackInputWrapper
En plus, c'est déjà sur la prod

![image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/1521862/599d23de-2300-4a2d-8e39-a6e4dfda4fa2)

2024-02-26 15:44 UTC, JulienParis commented on packages/web/src/components/tracks/TeeTrackInput.vue
> +  <TeeTrackInputWrapper
ah faudra que tu me précises quel est le browser que tu utilises, en attendant de mon côté sur Firefox/macOS je n'ai pas le clearable =>

![Capture d’écran 2024-02-26 à 10 43 31](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/3a125992-3d7e-42fa-b356-c341a32a97f5)

2024-02-26 17:28 UTC, JulienParis commented on packages/web/src/components/tracks/TeeTrackInput.vue
> +  <TeeTrackInputWrapper
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-search-cancel-button

<img width="1168" alt="Capture d’écran 2024-02-26 à 12 28 14" src="https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/21986727/ae6d6cda-b32d-41a2-b559-6ef812f01429">

2024-02-28 10:59 UTC, yvalentin requested changes
Ok , merci pour les explications... J'avais pas vu que ce n'était pas compatible avec firefox (je suis sous chrome pour TEE, normalement sous firefox mais j'ai centralisé le projet TEE sous chrome).

Pour le input search, très bien pour la solution proposée. Par contre, est-il possible de créer un composant dédié (TeeDsfrSearchBar ?)

2024-03-06 09:25 UTC, yvalentin commented
Je voulais dire juste renommer `TeeTrackInput` en `TeeDsfrSearchBar`

2024-03-11 08:59 UTC, yvalentin approved these changes

2024-03-11 14:14 UTC, yvalentin commented on packages/web/public/css/custom.css
> +.tee-btn-input-clear-btn-disabled {
suggestion: ici, on peux utiliser speudo class :disabled

```

2024-03-12 19:10 UTC, JulienParis commented on packages/web/src/components/tracks/TeeDsfrSearchBar.vue
> +  <form class="tee-form-input-large">
repassé en `div`

2024-03-18 18:12 UTC, merged