fix: move programs json generated from web to data package :package:
betagouv/transition-ecologique-entreprises-widget pull request #676
Opened 2024-04-08 13:43 UTC by yvalentin

2024-04-10 16:06 UTC, ttdm requested changes
Tu as oublié quelques changements pour que la refacto soit fonctionnelle. 

Et j'ai une question sur les gitignore.

2024-04-10 16:06 UTC, ttdm commented on packages/data/public/generated/.gitignore
> +!.gitignore
puis sur les gitignore, ici, tu ignore à nouveau tout dans le dossier sauf le gitignore. 
autant continuer d'ignorer le dossier initialement non ?

2024-04-10 16:06 UTC, ttdm commented on packages/data/src/dataPipeline.ts
> +
ça ne suffit pas pour effectuer le changement : 
l84, la path prioritaire est une variable d'environnement qui est set à :
DATA_FRONT_GENERATED_DIR_PATH=../../web/public/data/generated

Si tu veux faire ces changements, n'oublie pas de changer les variables d'environnement dans Scalingo aussi.

2024-04-11 08:38 UTC, yvalentin commented on .gitignore
> +!packages/data/public/generated/
Oui, à la base, je souhaite juste mettre, le fichier `.gitignore` dans le dossier `packages/data/public/generated`
C'est une alternative à `gitkeep` (https://dev.to/ritaly/git-lesson-how-to-use-gitignore-and-gitkeep-5edm)

Mais ça ne fonctionnait pas comme voulu ! Je n'ai pas trouvé d'autre moyen (après plus de 30 min dessus, ce qui est bien trop !!)

Bon, et maintenant, j'ai pu supprimé cette ligne et garder mon arborescence de dossier !!

2024-04-11 09:01 UTC, yvalentin commented on packages/data/src/dataPipeline.ts
> +
Cette variable d'environnement n'est pas utilisé et pas dans scalingo non plus (surement du legacy non nettoyé) (comme `VITE_DATA_DIR_PATH` aussi).
J'ai donc repris et nettoyer tout ça !

Merci pour ta vigilance ;-)

2024-04-11 09:04 UTC, yvalentin commented on packages/data/public/generated/.gitignore
> +!.gitignore
cf: le  commentaire ci-dessus

2024-04-11 12:21 UTC, ttdm commented on packages/data/src/dataPipeline.ts
> +
Désolé de ne pas avoir précisé : 
La variable d'environnement est définie dans packages/data :
https://github.com/betagouv/transition-ecologique-entreprises-widget/blob/main/packages/data/.env.example
Elle ne sert effectivement que dans dataPipeline et comme tu viens de la supprimer du fichier, elle ne sert donc plus et peut être nettoyée de packages/data/.env.example

Si tu supprimes, VITE_DATA_DIR_PATH, il faut que tu la supprimes de l'interface 
https://github.com/betagouv/transition-ecologique-entreprises-widget/blob/main/packages/web/src/env.d.ts
et du readme : 
https://github.com/betagouv/transition-ecologique-entreprises-widget/blob/main/packages/web/README.md

2024-04-11 20:15 UTC, yvalentin commented on packages/data/src/dataPipeline.ts
> +
Done !
Merci pour le signalement des oublies :ok_hand:

2024-04-12 08:35 UTC, ttdm approved these changes

2024-04-12 09:58 UTC, merged